### ISSUE TITLE
Error connection message in Database Tree when run count in bugged Distributed table.

### ISSUE THREAD

**Issue by perez1987** [HouseOps/HouseOps#10]
Hello!

I'm doing connection tests. My development clickhouse works perfectly but the production one does not get connected.

Give this error for all tables:

![image](https://user-images.githubusercontent.com/13163511/40776658-aa284578-64cb-11e8-9b9a-f403b02ee8da.png)

However, I have Tabix and other clients (dbeaver for example) and it works without problems in  production connection clickhouse

Thank you!pb

**Comment by jonatasfreitasv** [comment]
Hi @perez1987!

What is your HosueOps version?
What is your ClickHouse Server version?

You connect in ClickHouse Proxy or Server, in production?

Would you be able to start HouseOps with `npm run dev`, try to connect to your database and send me the stack of errors that will appear on the Console?

Thx a lot for your issue.

**Comment by perez1987** [comment]
Hi!

HosueOps --> Beta 1.0.0
CH Pro --> 1.1.54370
CH Dev--> 1.1.54362

Connect to CH Server

I send you the log via mail @jonatasfreitasv

**Comment by jonatasfreitasv** [comment]
Hi @perez1987, I received, but I need HouseOps log, please run HouseOps, clone this repo and run `npm install && npm start dev`.
 
Open dev console with CTRL+SHIFT+I.

Thx a lot again.

**Comment by perez1987** [comment]
@jonatasfreitasv  I send you the capture

![image](https://user-images.githubusercontent.com/13163511/40908267-86e71b52-67e6-11e8-9729-b1f719ae4d00.png)

**Comment by jonatasfreitasv** [comment]
Hi @perez1987, have a new version, test connection plz!

I added a button for open DevTools for debug in production ;).

**Comment by perez1987** [comment]
Thx for new version but doesnt works :-( @jonatasfreitasv  with my version 1.1.54370

![image](https://user-images.githubusercontent.com/13163511/41062680-d5282e4a-69d6-11e8-812e-136b9b81c669.png)

**Comment by jonatasfreitasv** [comment]
@perez1987 In DevTools, open network tab and see logs plz!

**Comment by perez1987** [comment]
It works already @jonatasfreitasv ! The problem was on my side. I had a distributed table that did not have a local table on one of the nodes. It was not a version problem.
Maybe that check should not cause the tables in HouseOps not to show up, do not you think? I explain?
Tabix for example does not do it.

**Comment by jonatasfreitasv** [comment]
@perez1987 Wow, nice, I'm fix this in next version, thx a lot.

**Comment by jonatasfreitasv** [comment]
This bug is fixed in v0.3.0-beta, thx @perez1987!
