### ISSUE TITLE
Quote table names to support numbers

### ISSUE THREAD

**Issue by Slind14** [HouseOps/HouseOps#43]
When using table names starting or ending with a number the following error occurs. This can be resolved by quoting the table name e.g. 

    `4fkjsdkfj`

![image](https://user-images.githubusercontent.com/3914677/44241675-b7dad000-a1c5-11e8-8a6a-bad081e76cee.png)

**Comment by jonatasfreitasv** [comment]
Hi @Slind14, thx for report this bug.
