### ISSUE TITLE
Production version on Windows not start

### ISSUE THREAD

**Issue by Mingdr** [HouseOps/HouseOps#6]
when i install HouseOps in win10,i get the error
![3e8dypj cb bdd2kpxynr3](https://user-images.githubusercontent.com/16832088/40471953-bffd698e-5f6a-11e8-995c-b186fc7c3204.png)
is it my java-sdk problem or the other, thanks

**Comment by jonatasfreitasv** [comment]
Hi @Mingdr, if you clone repo and run npm run dev?

Or try to build you, with npm run package.

Thx a lot for your report.

**Comment by Mingdr** [comment]
I downloaded the installation package of windows and installed . package:
![0m_nn_la9ir2 odijd h f](https://user-images.githubusercontent.com/16832088/40593458-48b70a30-625b-11e8-8e00-770d1054e0a1.png)
I'm not using npm

**Comment by Mingdr** [comment]
The url is in homepage:
https://github.com/HouseOps/HouseOps/releases/download/0.0.4-alpha/HouseOps.Setup.0.0.4.exe

**Comment by jonatasfreitasv** [comment]
@Mingdr try again pls!

**Comment by Mingdr** [comment]
thanks ~

**Comment by jonatasfreitasv** [comment]
@Mingdr Work?

**Comment by Mingdr** [comment]
no,the same problem,even though i use admin privilege to install and open.

**Comment by jonatasfreitasv** [comment]
Hummm, I make some tests and fix.

Thx a lot for your report @Mingdr.

**Comment by jonatasfreitasv** [comment]
Fixed on version 0.3.0-beta!

**Comment by jonatasfreitasv** [comment]
@Mingdr test plz!
